---
- name: install redis
  yum: name=redis state=installed
  tags:
    - redis
    - packages

- name: configure redis
  template: src="{{ item }}.j2" dest="/etc/{{ item }}"
  with_items:
    - redis.conf
    - redis-sentinel.conf
  notify: restart redis
  tags:
    - redis
    - configuration

- name: ensure redis is enabled
  service: name=redis enabled=yes
  notify: restart redis
  tags:
    - redis
    - configuration

- name: configure firewalld for redis
  firewalld: zone=public port=6379/tcp permanent=true state=enabled
  notify: reload firewall
  when: ansible_distribution_major_version|int == 7
  tags:
    - redis
    - firewall
    - configuration
